---
env:
  browser: true
  es6: true
extends: "eslint:recommended"
globals: []
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: "module"
rules:
  array-bracket-spacing: error
  array-callback-return: error
  block-scoped-var: error
  block-spacing: "error"
  brace-style: ["error", "1tbs", { allowSingleLine: true }]
  camelcase: error
  comma-dangle: ["error", "always-multiline"]
  comma-style: error
  complexity: error
  curly: error
  default-case: error
  eol-last: error
  eqeqeq: ["error", "smart"]
  func-call-spacing: error
  indent: ["error", 2]
  max-len: ["error", 120]
  no-caller: error
  no-catch-shadow: error
  no-lonely-if: error
  no-loop-func: error
  no-multiple-empty-lines: error
  no-param-reassign: error
  no-redeclare: error
  no-shadow: error
  no-ternary: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-unused-expressions: error
  no-with: error
  one-var: ["error", "never"]
  prefer-const: error
  prefer-spread: error
  quotes: ["error", "double", { avoidEscape: true }]
  require-await: error
  semi: ["error", "always", { omitLastInOneLineBlock: true }]
  space-before-blocks: error
  vars-on-top: error
  wrap-iife:
    - error
    - inside
  yoda: error
